web:
  build: .
  environment:
    - PORT=8080
    - LOG_LEVEL=info
    - LOG_LEVEL=debug
    - ENV=local
    - STATSD_ENABLED=false
    - STATSD_HOST=datadog
    - STATSD_PORT=8125
  ports:
    - "8080:8080"
  links:
#    - datadog
     - mongodb
  volumes:
  - ./server:/usr/src/app/server
  - ./test:/usr/src/app/test
  - ./package.json:/usr/src/app/package.json
  command: npm run dev


webonly:
  build: .
  environment:
    - PORT=8080
    - LOG_LEVEL=info
    - LOG_LEVEL=debug
    - ENV=local
    - STATSD_ENABLED=false
    - STATSD_HOST=datadog
    - STATSD_PORT=8125
  ports:
    - "8080:8080"
  links:
#    - datadog
     - mongodb
  volumes:
  - ./server:/usr/src/app/server
  - ./test:/usr/src/app/test
  - ./package.json:/usr/src/app/package.json
  command: npm start


#datadog:
#  image: datadog/docker-dd-agent
#  environment:
#     - API_KEY=__your_datadog_api_key_here__
#     - DOGSTATSD_ONLY=true
#  volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
#    - /proc/mounts:/host/proc/mounts:ro
#    - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
#  ports:
#    - "8125:8125/udp"

mongodb:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles"

acceptance_test:
  build: server/test/acceptance-test
  environment:
    - SERVICE_BASE_URL=http://webonly:8080
  working_dir: /usr/src/acceptance-test
  links:
    - webonly
  volumes:
    - ./server/test/acceptance-test/test:/usr/src/acceptance-test/test
  command: npm start
